import React, { Component } from 'react';
import CssBaseline from '@material-ui/core/CssBaseline';
import Typography from '@material-ui/core/Typography';
import img from '../../images/MainRoom.png';
import { styles } from "../../styles";

export default class Main extends Component {
    render() {
        return (
            <>
                <CssBaseline />
                {/* Image Map Generated by http://www.image-map.net/ */}
                <img style={styles.Img} src={img} alt="map" useMap="#map" />
                <map name="map">
                </map>
            </>
        );
    }
}
