import React, { Component } from "react"
import CssBaseline from "@material-ui/core/CssBaseline"
import axios from "axios"
import { Typography, Popover } from "@material-ui/core"
import { withStyles } from "@material-ui/styles"

const useStyles = (theme) => ({
  popover: {
    pointerEvents: "none",
  },
  paper: {
    padding: theme.spacing(1),
  },
})

class Map extends Component {
  constructor(props) {
    super(props)
    this.state = {
      name: null,
      solved_puzzles: 0,
      solved: 0,
      anchorEl: null,
    }
  }

  componentDidMount() {
    this.getSolvedPuzzles()
  }

  getSolvedPuzzles = () => {
    axios
      .get(`/api/team/${this.props.teamId}/`)
      .then((res) => {
        this.setState({
          solved_puzzles: parseInt(res.data.puzzles_done),
        })
      })
      .catch((err) => {
        console.error(err)
      })
  }

  handlePopoverOpen = (event) => {
    const id = parseInt(event.currentTarget.getAttribute("alt"))

    this.setState({
      name: event.currentTarget.getAttribute("title"),
      solved: this.state.solved_puzzles & (1 << (id - 1)),
      anchorEl: event.currentTarget,
    })
  }

  handlePopoverClose = () => {
    this.setState({
      anchorEl: null,
    })
  }

  render() {
    const open = Boolean(this.state.anchorEl)

    return (
      <>
        <CssBaseline />
        {/* Image Map Generated by https://12oss.github.io/linkresponsively/ */}
        <div style={{ float: "left", position: "relative", width: "100%" }}>
          <img src="map.png" width="100%" />
          <a
            title="Puzzle 1"
            href="/"
            aria-owns={open ? "mouse-over-popover" : undefined}
            aria-haspopup="true"
            onMouseEnter={this.handlePopoverOpen}
            onMouseLeave={this.handlePopoverClose}
            style={{
              width: "20.2%",
              height: "17.3%",
              left: "45.0%",
              top: "31.8%",
              position: "absolute",
              cursor: "pointer",
              display: "block",
              zIndex: "5",
              overflow: "hidden",
            }}
          />
          <a
            title="Puzzle 2"
            href="/puzzle"
            aria-owns={open ? "mouse-over-popover" : undefined}
            aria-haspopup="true"
            onMouseEnter={this.handlePopoverOpen}
            onMouseLeave={this.handlePopoverClose}
            style={{
              width: "19.3%",
              height: "16.5%",
              left: "4.8%",
              top: "63.6%",
              position: "absolute",
              cursor: "pointer",
              display: "block",
              zIndex: "5",
              overflow: "hidden",
            }}
          />
          <Popover
            id="mouse-over-popover"
            className={this.props.classes.popover}
            classes={{
              paper: this.props.classes.paper,
            }}
            open={open}
            anchorEl={this.state.anchorEl}
            anchorOrigin={{
              vertical: "bottom",
              horizontal: "left",
            }}
            transformOrigin={{
              vertical: "top",
              horizontal: "left",
            }}
            onClose={this.handlePopoverClose}
            disableRestoreFocus
          >
            <Typography>
              <h3>{this.state.name}</h3>
              {this.state.solved === 1 ? <p>Solved!</p> : <p> Not solved</p>}
            </Typography>
          </Popover>
        </div>
      </>
    )
  }
}
export default withStyles(useStyles)(Map)
